### ISSUE TITLE
Receive FrozenError when record is saved.

### ISSUE THREAD

**Issue by nilay** [celsodantas/protokoll#37]
Ruby: 2.7.1
Rails: 6.0.2
Error: <FrozenError: can't modify frozen String: \"\">

```
"Framework Trace": [
            {
                "exception_object_id": 34380,
                "id": 0,
                "trace": "protokoll (2.0.1) lib/protokoll/formater.rb:64:in `sub!'"
            },
            {
                "exception_object_id": 34380,
                "id": 1,
                "trace": "protokoll (2.0.1) lib/protokoll/formater.rb:64:in `expand_times'"
            },
            {
                "exception_object_id": 34380,
                "id": 2,
                "trace": "protokoll (2.0.1) lib/protokoll/formater.rb:44:in `sufix'"
            },
            {
                "exception_object_id": 34380,
                "id": 3,
                "trace": "protokoll (2.0.1) lib/protokoll/formater.rb:30:in `build'"
            },
            {
                "exception_object_id": 34380,
                "id": 4,
                "trace": "protokoll (2.0.1) lib/protokoll/formater.rb:7:in `format'"
            },
            {
                "exception_object_id": 34380,
                "id": 5,
                "trace": "protokoll (2.0.1) lib/protokoll/counter.rb:16:in `next'"
            },
            {
                "exception_object_id": 34380,
                "id": 6,
                "trace": "protokoll (2.0.1) lib/protokoll/protokoll.rb:32:in `block in protokoll'"
            },
            {
                "exception_object_id": 34380,
                "id": 7,
                "trace": "activesupport (6.0.2.2) lib/active_support/callbacks.rb:429:in `instance_exec'"
            },
            {
                "exception_object_id": 34380,
                "id": 8,
                "trace": "activesupport (6.0.2.2) lib/active_support/callbacks.rb:429:in `block in make_lambda'"
            },
            {
                "exception_object_id": 34380,
                "id": 9,
                "trace": "activesupport (6.0.2.2) lib/active_support/callbacks.rb:201:in `block (2 levels) in halting'"
            },
            {
                "exception_object_id": 34380,
                "id": 10,
                "trace": "activesupport (6.0.2.2) lib/active_support/callbacks.rb:607:in `block (2 levels) in default_terminator'"
            },
            {
                "exception_object_id": 34380,
                "id": 11,
                "trace": "activesupport (6.0.2.2) lib/active_support/callbacks.rb:606:in `catch'"
            },
            {
                "exception_object_id": 34380,
                "id": 12,
                "trace": "activesupport (6.0.2.2) lib/active_support/callbacks.rb:606:in `block in default_terminator'"
            },
            {
                "exception_object_id": 34380,
                "id": 13,
                "trace": "activesupport (6.0.2.2) lib/active_support/callbacks.rb:202:in `block in halting'"
            },
            {
                "exception_object_id": 34380,
                "id": 14,
                "trace": "activesupport (6.0.2.2) lib/active_support/callbacks.rb:514:in `block in invoke_before'"
            },
            {
                "exception_object_id": 34380,
                "id": 15,
                "trace": "activesupport (6.0.2.2) lib/active_support/callbacks.rb:514:in `each'"
            },
            {
                "exception_object_id": 34380,
                "id": 16,
                "trace": "activesupport (6.0.2.2) lib/active_support/callbacks.rb:514:in `invoke_before'"
            },
            {
                "exception_object_id": 34380,
                "id": 17,
                "trace": "activesupport (6.0.2.2) lib/active_support/callbacks.rb:134:in `run_callbacks'"
            },
            {
                "exception_object_id": 34380,
                "id": 18,
                "trace": "activesupport (6.0.2.2) lib/active_support/callbacks.rb:827:in `_run_create_callbacks'"
            },
            {
                "exception_object_id": 34380,
                "id": 19,
                "trace": "activerecord (6.0.2.2) lib/active_record/callbacks.rb:332:in `_create_record'"
            },
            {
                "exception_object_id": 34380,
                "id": 20,
                "trace": "activerecord (6.0.2.2) lib/active_record/timestamp.rb:111:in `_create_record'"
            },
            {
                "exception_object_id": 34380,
                "id": 21,
                "trace": "activerecord (6.0.2.2) lib/active_record/persistence.rb:906:in `create_or_update'"
            },
            {
                "exception_object_id": 34380,
                "id": 22,
                "trace": "activerecord (6.0.2.2) lib/active_record/callbacks.rb:328:in `block in create_or_update'"
            },
            {
                "exception_object_id": 34380,
                "id": 23,
                "trace": "activesupport (6.0.2.2) lib/active_support/callbacks.rb:135:in `run_callbacks'"
            },
            {
                "exception_object_id": 34380,
                "id": 24,
                "trace": "activesupport (6.0.2.2) lib/active_support/callbacks.rb:827:in `_run_save_callbacks'"
            },
            {
                "exception_object_id": 34380,
                "id": 25,
                "trace": "activerecord (6.0.2.2) lib/active_record/callbacks.rb:328:in `create_or_update'"
            },
            {
                "exception_object_id": 34380,
                "id": 26,
                "trace": "activerecord (6.0.2.2) lib/active_record/timestamp.rb:129:in `create_or_update'"
            },
            {
                "exception_object_id": 34380,
                "id": 27,
                "trace": "activerecord (6.0.2.2) lib/active_record/persistence.rb:470:in `save'"
            },
            {
                "exception_object_id": 34380,
                "id": 28,
                "trace": "activerecord (6.0.2.2) lib/active_record/validations.rb:47:in `save'"
            },
            {
                "exception_object_id": 34380,
                "id": 29,
                "trace": "activerecord (6.0.2.2) lib/active_record/transactions.rb:315:in `block in save'"
            },
            {
                "exception_object_id": 34380,
                "id": 30,
                "trace": "activerecord (6.0.2.2) lib/active_record/transactions.rb:375:in `block in with_transaction_returning_status'"
            },
            {
                "exception_object_id": 34380,
                "id": 31,
                "trace": "activerecord (6.0.2.2) lib/active_record/connection_adapters/abstract/database_statements.rb:281:in `block in transaction'"
            },
            {
                "exception_object_id": 34380,
                "id": 32,
                "trace": "activerecord (6.0.2.2) lib/active_record/connection_adapters/abstract/transaction.rb:280:in `block in within_new_transaction'"
            },
            {
                "exception_object_id": 34380,
                "id": 33,
                "trace": "activerecord (6.0.2.2) lib/active_record/connection_adapters/abstract/transaction.rb:278:in `synchronize'"
            },
            {
                "exception_object_id": 34380,
                "id": 34,
                "trace": "activerecord (6.0.2.2) lib/active_record/connection_adapters/abstract/transaction.rb:278:in `within_new_transaction'"
            },
            {
                "exception_object_id": 34380,
                "id": 35,
                "trace": "activerecord (6.0.2.2) lib/active_record/connection_adapters/abstract/database_statements.rb:281:in `transaction'"
            },
            {
                "exception_object_id": 34380,
                "id": 36,
                "trace": "activerecord (6.0.2.2) lib/active_record/transactions.rb:212:in `transaction'"
            },
            {
                "exception_object_id": 34380,
                "id": 37,
                "trace": "activerecord (6.0.2.2) lib/active_record/transactions.rb:366:in `with_transaction_returning_status'"
            },
            {
                "exception_object_id": 34380,
                "id": 38,
                "trace": "activerecord (6.0.2.2) lib/active_record/transactions.rb:315:in `save'"
            },
            {
                "exception_object_id": 34380,
                "id": 39,
                "trace": "activerecord (6.0.2.2) lib/active_record/suppressor.rb:44:in `save'"
            },
            {
                "exception_object_id": 34380,
                "id": 42,
                "trace": "actionpack (6.0.2.2) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'"
            },
            {
                "exception_object_id": 34380,
                "id": 43,
                "trace": "actionpack (6.0.2.2) lib/abstract_controller/base.rb:196:in `process_action'"
            },
            {
                "exception_object_id": 34380,
                "id": 44,
                "trace": "actionpack (6.0.2.2) lib/action_controller/metal/rendering.rb:30:in `process_action'"
            },
            {
                "exception_object_id": 34380,
                "id": 45,
                "trace": "actionpack (6.0.2.2) lib/abstract_controller/callbacks.rb:42:in `block in process_action'"
            },
            {
                "exception_object_id": 34380,
                "id": 46,
                "trace": "activesupport (6.0.2.2) lib/active_support/callbacks.rb:112:in `block in run_callbacks'"
            },
            {
                "exception_object_id": 34380,
                "id": 47,
                "trace": "consul (1.0.3) lib/consul/controller.rb:103:in `with_current_power'"
            },
            {
                "exception_object_id": 34380,
                "id": 48,
                "trace": "activesupport (6.0.2.2) lib/active_support/callbacks.rb:121:in `block in run_callbacks'"
            },
            {
                "exception_object_id": 34380,
                "id": 49,
                "trace": "activesupport (6.0.2.2) lib/active_support/callbacks.rb:139:in `run_callbacks'"
            },
            {
                "exception_object_id": 34380,
                "id": 50,
                "trace": "actionpack (6.0.2.2) lib/abstract_controller/callbacks.rb:41:in `process_action'"
            },
            {
                "exception_object_id": 34380,
                "id": 51,
                "trace": "actionpack (6.0.2.2) lib/action_controller/metal/rescue.rb:22:in `process_action'"
            },
            {
                "exception_object_id": 34380,
                "id": 52,
                "trace": "actionpack (6.0.2.2) lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'"
            },
            {
                "exception_object_id": 34380,
                "id": 53,
                "trace": "activesupport (6.0.2.2) lib/active_support/notifications.rb:180:in `block in instrument'"
            },
            {
                "exception_object_id": 34380,
                "id": 54,
                "trace": "activesupport (6.0.2.2) lib/active_support/notifications/instrumenter.rb:24:in `instrument'"
            },
            {
                "exception_object_id": 34380,
                "id": 55,
                "trace": "activesupport (6.0.2.2) lib/active_support/notifications.rb:180:in `instrument'"
            },
            {
                "exception_object_id": 34380,
                "id": 56,
                "trace": "actionpack (6.0.2.2) lib/action_controller/metal/instrumentation.rb:32:in `process_action'"
            },
            {
                "exception_object_id": 34380,
                "id": 57,
                "trace": "actionpack (6.0.2.2) lib/action_controller/metal/params_wrapper.rb:245:in `process_action'"
            },
            {
                "exception_object_id": 34380,
                "id": 58,
                "trace": "activerecord (6.0.2.2) lib/active_record/railties/controller_runtime.rb:27:in `process_action'"
            },
            {
                "exception_object_id": 34380,
                "id": 59,
                "trace": "actionpack (6.0.2.2) lib/abstract_controller/base.rb:136:in `process'"
            },
            {
                "exception_object_id": 34380,
                "id": 60,
                "trace": "actionpack (6.0.2.2) lib/action_controller/metal.rb:191:in `dispatch'"
            },
            {
                "exception_object_id": 34380,
                "id": 61,
                "trace": "actionpack (6.0.2.2) lib/action_controller/metal.rb:252:in `dispatch'"
            },
            {
                "exception_object_id": 34380,
                "id": 62,
                "trace": "actionpack (6.0.2.2) lib/action_dispatch/routing/route_set.rb:51:in `dispatch'"
            },
            {
                "exception_object_id": 34380,
                "id": 63,
                "trace": "actionpack (6.0.2.2) lib/action_dispatch/routing/route_set.rb:33:in `serve'"
            },
            {
                "exception_object_id": 34380,
                "id": 64,
                "trace": "actionpack (6.0.2.2) lib/action_dispatch/journey/router.rb:49:in `block in serve'"
            },
            {
                "exception_object_id": 34380,
                "id": 65,
                "trace": "actionpack (6.0.2.2) lib/action_dispatch/journey/router.rb:32:in `each'"
            },
            {
                "exception_object_id": 34380,
                "id": 66,
                "trace": "actionpack (6.0.2.2) lib/action_dispatch/journey/router.rb:32:in `serve'"
            },
            {
                "exception_object_id": 34380,
                "id": 67,
                "trace": "actionpack (6.0.2.2) lib/action_dispatch/routing/route_set.rb:837:in `call'"
            },
            {
                "exception_object_id": 34380,
                "id": 68,
                "trace": "rack (2.2.2) lib/rack/etag.rb:27:in `call'"
            },
            {
                "exception_object_id": 34380,
                "id": 69,
                "trace": "rack (2.2.2) lib/rack/conditional_get.rb:40:in `call'"
            },
            {
                "exception_object_id": 34380,
                "id": 70,
                "trace": "rack (2.2.2) lib/rack/head.rb:12:in `call'"
            },
            {
                "exception_object_id": 34380,
                "id": 71,
                "trace": "activerecord (6.0.2.2) lib/active_record/migration.rb:567:in `call'"
            },
            {
                "exception_object_id": 34380,
                "id": 72,
                "trace": "actionpack (6.0.2.2) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'"
            },
            {
                "exception_object_id": 34380,
                "id": 73,
                "trace": "activesupport (6.0.2.2) lib/active_support/callbacks.rb:101:in `run_callbacks'"
            },
            {
                "exception_object_id": 34380,
                "id": 74,
                "trace": "actionpack (6.0.2.2) lib/action_dispatch/middleware/callbacks.rb:26:in `call'"
            },
            {
                "exception_object_id": 34380,
                "id": 75,
                "trace": "actionpack (6.0.2.2) lib/action_dispatch/middleware/executor.rb:14:in `call'"
            },
            {
                "exception_object_id": 34380,
                "id": 76,
                "trace": "actionpack (6.0.2.2) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'"
            },
            {
                "exception_object_id": 34380,
                "id": 77,
                "trace": "actionpack (6.0.2.2) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'"
            },
            {
                "exception_object_id": 34380,
                "id": 78,
                "trace": "actionpack (6.0.2.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'"
            },
            {
                "exception_object_id": 34380,
                "id": 79,
                "trace": "railties (6.0.2.2) lib/rails/rack/logger.rb:38:in `call_app'"
            },
            {
                "exception_object_id": 34380,
                "id": 80,
                "trace": "railties (6.0.2.2) lib/rails/rack/logger.rb:26:in `block in call'"
            },
            {
                "exception_object_id": 34380,
                "id": 81,
                "trace": "activesupport (6.0.2.2) lib/active_support/tagged_logging.rb:80:in `block in tagged'"
            },
            {
                "exception_object_id": 34380,
                "id": 82,
                "trace": "activesupport (6.0.2.2) lib/active_support/tagged_logging.rb:28:in `tagged'"
            },
            {
                "exception_object_id": 34380,
                "id": 83,
                "trace": "activesupport (6.0.2.2) lib/active_support/tagged_logging.rb:80:in `tagged'"
            },
            {
                "exception_object_id": 34380,
                "id": 84,
                "trace": "railties (6.0.2.2) lib/rails/rack/logger.rb:26:in `call'"
            },
            {
                "exception_object_id": 34380,
                "id": 85,
                "trace": "actionpack (6.0.2.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'"
            },
            {
                "exception_object_id": 34380,
                "id": 86,
                "trace": "request_store (1.5.0) lib/request_store/middleware.rb:19:in `call'"
            },
            {
                "exception_object_id": 34380,
                "id": 87,
                "trace": "actionpack (6.0.2.2) lib/action_dispatch/middleware/request_id.rb:27:in `call'"
            },
            {
                "exception_object_id": 34380,
                "id": 88,
                "trace": "rack (2.2.2) lib/rack/runtime.rb:22:in `call'"
            },
            {
                "exception_object_id": 34380,
                "id": 89,
                "trace": "activesupport (6.0.2.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'"
            },
            {
                "exception_object_id": 34380,
                "id": 90,
                "trace": "actionpack (6.0.2.2) lib/action_dispatch/middleware/executor.rb:14:in `call'"
            },
            {
                "exception_object_id": 34380,
                "id": 91,
                "trace": "actionpack (6.0.2.2) lib/action_dispatch/middleware/static.rb:126:in `call'"
            },
            {
                "exception_object_id": 34380,
                "id": 92,
                "trace": "rack (2.2.2) lib/rack/sendfile.rb:110:in `call'"
            },
            {
                "exception_object_id": 34380,
                "id": 93,
                "trace": "actionpack (6.0.2.2) lib/action_dispatch/middleware/host_authorization.rb:83:in `call'"
            },
            {
                "exception_object_id": 34380,
                "id": 94,
                "trace": "rack-cors (1.1.1) lib/rack/cors.rb:100:in `call'"
            },
            {
                "exception_object_id": 34380,
                "id": 95,
                "trace": "railties (6.0.2.2) lib/rails/engine.rb:526:in `call'"
            },
            {
                "exception_object_id": 34380,
                "id": 96,
                "trace": "puma (4.3.3) lib/puma/configuration.rb:228:in `call'"
            },
            {
                "exception_object_id": 34380,
                "id": 97,
                "trace": "puma (4.3.3) lib/puma/server.rb:682:in `handle_request'"
            },
            {
                "exception_object_id": 34380,
                "id": 98,
                "trace": "puma (4.3.3) lib/puma/server.rb:472:in `process_client'"
            },
            {
                "exception_object_id": 34380,
                "id": 99,
                "trace": "puma (4.3.3) lib/puma/server.rb:328:in `block in run'"
            },
            {
                "exception_object_id": 34380,
                "id": 100,
                "trace": "puma (4.3.3) lib/puma/thread_pool.rb:134:in `block in spawn_thread'"
            }
        ],
        "Full Trace": [
            {
                "exception_object_id": 34380,
                "id": 0,
                "trace": "protokoll (2.0.1) lib/protokoll/formater.rb:64:in `sub!'"
            },
            {
                "exception_object_id": 34380,
                "id": 1,
                "trace": "protokoll (2.0.1) lib/protokoll/formater.rb:64:in `expand_times'"
            },
            {
                "exception_object_id": 34380,
                "id": 2,
                "trace": "protokoll (2.0.1) lib/protokoll/formater.rb:44:in `sufix'"
            },
            {
                "exception_object_id": 34380,
                "id": 3,
                "trace": "protokoll (2.0.1) lib/protokoll/formater.rb:30:in `build'"
            },
            {
                "exception_object_id": 34380,
                "id": 4,
                "trace": "protokoll (2.0.1) lib/protokoll/formater.rb:7:in `format'"
            },
            {
                "exception_object_id": 34380,
                "id": 5,
                "trace": "protokoll (2.0.1) lib/protokoll/counter.rb:16:in `next'"
            },
            {
                "exception_object_id": 34380,
                "id": 6,
                "trace": "protokoll (2.0.1) lib/protokoll/protokoll.rb:32:in `block in protokoll'"
            },
            {
                "exception_object_id": 34380,
                "id": 7,
                "trace": "activesupport (6.0.2.2) lib/active_support/callbacks.rb:429:in `instance_exec'"
            },
            {
                "exception_object_id": 34380,
                "id": 8,
                "trace": "activesupport (6.0.2.2) lib/active_support/callbacks.rb:429:in `block in make_lambda'"
            },
            {
                "exception_object_id": 34380,
                "id": 9,
                "trace": "activesupport (6.0.2.2) lib/active_support/callbacks.rb:201:in `block (2 levels) in halting'"
            },
            {
                "exception_object_id": 34380,
                "id": 10,
                "trace": "activesupport (6.0.2.2) lib/active_support/callbacks.rb:607:in `block (2 levels) in default_terminator'"
            },
            {
                "exception_object_id": 34380,
                "id": 11,
                "trace": "activesupport (6.0.2.2) lib/active_support/callbacks.rb:606:in `catch'"
            },
            {
                "exception_object_id": 34380,
                "id": 12,
                "trace": "activesupport (6.0.2.2) lib/active_support/callbacks.rb:606:in `block in default_terminator'"
            },
            {
                "exception_object_id": 34380,
                "id": 13,
                "trace": "activesupport (6.0.2.2) lib/active_support/callbacks.rb:202:in `block in halting'"
            },
            {
                "exception_object_id": 34380,
                "id": 14,
                "trace": "activesupport (6.0.2.2) lib/active_support/callbacks.rb:514:in `block in invoke_before'"
            },
            {
                "exception_object_id": 34380,
                "id": 15,
                "trace": "activesupport (6.0.2.2) lib/active_support/callbacks.rb:514:in `each'"
            },
            {
                "exception_object_id": 34380,
                "id": 16,
                "trace": "activesupport (6.0.2.2) lib/active_support/callbacks.rb:514:in `invoke_before'"
            },
            {
                "exception_object_id": 34380,
                "id": 17,
                "trace": "activesupport (6.0.2.2) lib/active_support/callbacks.rb:134:in `run_callbacks'"
            },
            {
                "exception_object_id": 34380,
                "id": 18,
                "trace": "activesupport (6.0.2.2) lib/active_support/callbacks.rb:827:in `_run_create_callbacks'"
            },
            {
                "exception_object_id": 34380,
                "id": 19,
                "trace": "activerecord (6.0.2.2) lib/active_record/callbacks.rb:332:in `_create_record'"
            },
            {
                "exception_object_id": 34380,
                "id": 20,
                "trace": "activerecord (6.0.2.2) lib/active_record/timestamp.rb:111:in `_create_record'"
            },
            {
                "exception_object_id": 34380,
                "id": 21,
                "trace": "activerecord (6.0.2.2) lib/active_record/persistence.rb:906:in `create_or_update'"
            },
            {
                "exception_object_id": 34380,
                "id": 22,
                "trace": "activerecord (6.0.2.2) lib/active_record/callbacks.rb:328:in `block in create_or_update'"
            },
            {
                "exception_object_id": 34380,
                "id": 23,
                "trace": "activesupport (6.0.2.2) lib/active_support/callbacks.rb:135:in `run_callbacks'"
            },
            {
                "exception_object_id": 34380,
                "id": 24,
                "trace": "activesupport (6.0.2.2) lib/active_support/callbacks.rb:827:in `_run_save_callbacks'"
            },
            {
                "exception_object_id": 34380,
                "id": 25,
                "trace": "activerecord (6.0.2.2) lib/active_record/callbacks.rb:328:in `create_or_update'"
            },
            {
                "exception_object_id": 34380,
                "id": 26,
                "trace": "activerecord (6.0.2.2) lib/active_record/timestamp.rb:129:in `create_or_update'"
            },
            {
                "exception_object_id": 34380,
                "id": 27,
                "trace": "activerecord (6.0.2.2) lib/active_record/persistence.rb:470:in `save'"
            },
            {
                "exception_object_id": 34380,
                "id": 28,
                "trace": "activerecord (6.0.2.2) lib/active_record/validations.rb:47:in `save'"
            },
            {
                "exception_object_id": 34380,
                "id": 29,
                "trace": "activerecord (6.0.2.2) lib/active_record/transactions.rb:315:in `block in save'"
            },
            {
                "exception_object_id": 34380,
                "id": 30,
                "trace": "activerecord (6.0.2.2) lib/active_record/transactions.rb:375:in `block in with_transaction_returning_status'"
            },
            {
                "exception_object_id": 34380,
                "id": 31,
                "trace": "activerecord (6.0.2.2) lib/active_record/connection_adapters/abstract/database_statements.rb:281:in `block in transaction'"
            },
            {
                "exception_object_id": 34380,
                "id": 32,
                "trace": "activerecord (6.0.2.2) lib/active_record/connection_adapters/abstract/transaction.rb:280:in `block in within_new_transaction'"
            },
            {
                "exception_object_id": 34380,
                "id": 33,
                "trace": "activerecord (6.0.2.2) lib/active_record/connection_adapters/abstract/transaction.rb:278:in `synchronize'"
            },
            {
                "exception_object_id": 34380,
                "id": 34,
                "trace": "activerecord (6.0.2.2) lib/active_record/connection_adapters/abstract/transaction.rb:278:in `within_new_transaction'"
            },
            {
                "exception_object_id": 34380,
                "id": 35,
                "trace": "activerecord (6.0.2.2) lib/active_record/connection_adapters/abstract/database_statements.rb:281:in `transaction'"
            },
            {
                "exception_object_id": 34380,
                "id": 36,
                "trace": "activerecord (6.0.2.2) lib/active_record/transactions.rb:212:in `transaction'"
            },
            {
                "exception_object_id": 34380,
                "id": 37,
                "trace": "activerecord (6.0.2.2) lib/active_record/transactions.rb:366:in `with_transaction_returning_status'"
            },
            {
                "exception_object_id": 34380,
                "id": 38,
                "trace": "activerecord (6.0.2.2) lib/active_record/transactions.rb:315:in `save'"
            },
            {
                "exception_object_id": 34380,
                "id": 39,
                "trace": "activerecord (6.0.2.2) lib/active_record/suppressor.rb:44:in `save'"
            },
            {
                "exception_object_id": 34380,
                "id": 40,
                "trace": "app/controllers/concerns/base_crud.rb:31:in `create'"
            },
            {
                "exception_object_id": 34380,
                "id": 41,
                "trace": "app/controllers/v1/compound/maintenance/requests_controller.rb:6:in `create'"
            },
            {
                "exception_object_id": 34380,
                "id": 42,
                "trace": "actionpack (6.0.2.2) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'"
            },
            {
                "exception_object_id": 34380,
                "id": 43,
                "trace": "actionpack (6.0.2.2) lib/abstract_controller/base.rb:196:in `process_action'"
            },
            {
                "exception_object_id": 34380,
                "id": 44,
                "trace": "actionpack (6.0.2.2) lib/action_controller/metal/rendering.rb:30:in `process_action'"
            },
            {
                "exception_object_id": 34380,
                "id": 45,
                "trace": "actionpack (6.0.2.2) lib/abstract_controller/callbacks.rb:42:in `block in process_action'"
            },
            {
                "exception_object_id": 34380,
                "id": 46,
                "trace": "activesupport (6.0.2.2) lib/active_support/callbacks.rb:112:in `block in run_callbacks'"
            },
            {
                "exception_object_id": 34380,
                "id": 47,
                "trace": "consul (1.0.3) lib/consul/controller.rb:103:in `with_current_power'"
            },
            {
                "exception_object_id": 34380,
                "id": 48,
                "trace": "activesupport (6.0.2.2) lib/active_support/callbacks.rb:121:in `block in run_callbacks'"
            },
            {
                "exception_object_id": 34380,
                "id": 49,
                "trace": "activesupport (6.0.2.2) lib/active_support/callbacks.rb:139:in `run_callbacks'"
            },
            {
                "exception_object_id": 34380,
                "id": 50,
                "trace": "actionpack (6.0.2.2) lib/abstract_controller/callbacks.rb:41:in `process_action'"
            },
            {
                "exception_object_id": 34380,
                "id": 51,
                "trace": "actionpack (6.0.2.2) lib/action_controller/metal/rescue.rb:22:in `process_action'"
            },
            {
                "exception_object_id": 34380,
                "id": 52,
                "trace": "actionpack (6.0.2.2) lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'"
            },
            {
                "exception_object_id": 34380,
                "id": 53,
                "trace": "activesupport (6.0.2.2) lib/active_support/notifications.rb:180:in `block in instrument'"
            },
            {
                "exception_object_id": 34380,
                "id": 54,
                "trace": "activesupport (6.0.2.2) lib/active_support/notifications/instrumenter.rb:24:in `instrument'"
            },
            {
                "exception_object_id": 34380,
                "id": 55,
                "trace": "activesupport (6.0.2.2) lib/active_support/notifications.rb:180:in `instrument'"
            },
            {
                "exception_object_id": 34380,
                "id": 56,
                "trace": "actionpack (6.0.2.2) lib/action_controller/metal/instrumentation.rb:32:in `process_action'"
            },
            {
                "exception_object_id": 34380,
                "id": 57,
                "trace": "actionpack (6.0.2.2) lib/action_controller/metal/params_wrapper.rb:245:in `process_action'"
            },
            {
                "exception_object_id": 34380,
                "id": 58,
                "trace": "activerecord (6.0.2.2) lib/active_record/railties/controller_runtime.rb:27:in `process_action'"
            },
            {
                "exception_object_id": 34380,
                "id": 59,
                "trace": "actionpack (6.0.2.2) lib/abstract_controller/base.rb:136:in `process'"
            },
            {
                "exception_object_id": 34380,
                "id": 60,
                "trace": "actionpack (6.0.2.2) lib/action_controller/metal.rb:191:in `dispatch'"
            },
            {
                "exception_object_id": 34380,
                "id": 61,
                "trace": "actionpack (6.0.2.2) lib/action_controller/metal.rb:252:in `dispatch'"
            },
            {
                "exception_object_id": 34380,
                "id": 62,
                "trace": "actionpack (6.0.2.2) lib/action_dispatch/routing/route_set.rb:51:in `dispatch'"
            },
            {
                "exception_object_id": 34380,
                "id": 63,
                "trace": "actionpack (6.0.2.2) lib/action_dispatch/routing/route_set.rb:33:in `serve'"
            },
            {
                "exception_object_id": 34380,
                "id": 64,
                "trace": "actionpack (6.0.2.2) lib/action_dispatch/journey/router.rb:49:in `block in serve'"
            },
            {
                "exception_object_id": 34380,
                "id": 65,
                "trace": "actionpack (6.0.2.2) lib/action_dispatch/journey/router.rb:32:in `each'"
            },
            {
                "exception_object_id": 34380,
                "id": 66,
                "trace": "actionpack (6.0.2.2) lib/action_dispatch/journey/router.rb:32:in `serve'"
            },
            {
                "exception_object_id": 34380,
                "id": 67,
                "trace": "actionpack (6.0.2.2) lib/action_dispatch/routing/route_set.rb:837:in `call'"
            },
            {
                "exception_object_id": 34380,
                "id": 68,
                "trace": "rack (2.2.2) lib/rack/etag.rb:27:in `call'"
            },
            {
                "exception_object_id": 34380,
                "id": 69,
                "trace": "rack (2.2.2) lib/rack/conditional_get.rb:40:in `call'"
            },
            {
                "exception_object_id": 34380,
                "id": 70,
                "trace": "rack (2.2.2) lib/rack/head.rb:12:in `call'"
            },
            {
                "exception_object_id": 34380,
                "id": 71,
                "trace": "activerecord (6.0.2.2) lib/active_record/migration.rb:567:in `call'"
            },
            {
                "exception_object_id": 34380,
                "id": 72,
                "trace": "actionpack (6.0.2.2) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'"
            },
            {
                "exception_object_id": 34380,
                "id": 73,
                "trace": "activesupport (6.0.2.2) lib/active_support/callbacks.rb:101:in `run_callbacks'"
            },
            {
                "exception_object_id": 34380,
                "id": 74,
                "trace": "actionpack (6.0.2.2) lib/action_dispatch/middleware/callbacks.rb:26:in `call'"
            },
            {
                "exception_object_id": 34380,
                "id": 75,
                "trace": "actionpack (6.0.2.2) lib/action_dispatch/middleware/executor.rb:14:in `call'"
            },
            {
                "exception_object_id": 34380,
                "id": 76,
                "trace": "actionpack (6.0.2.2) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'"
            },
            {
                "exception_object_id": 34380,
                "id": 77,
                "trace": "actionpack (6.0.2.2) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'"
            },
            {
                "exception_object_id": 34380,
                "id": 78,
                "trace": "actionpack (6.0.2.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'"
            },
            {
                "exception_object_id": 34380,
                "id": 79,
                "trace": "railties (6.0.2.2) lib/rails/rack/logger.rb:38:in `call_app'"
            },
            {
                "exception_object_id": 34380,
                "id": 80,
                "trace": "railties (6.0.2.2) lib/rails/rack/logger.rb:26:in `block in call'"
            },
            {
                "exception_object_id": 34380,
                "id": 81,
                "trace": "activesupport (6.0.2.2) lib/active_support/tagged_logging.rb:80:in `block in tagged'"
            },
            {
                "exception_object_id": 34380,
                "id": 82,
                "trace": "activesupport (6.0.2.2) lib/active_support/tagged_logging.rb:28:in `tagged'"
            },
            {
                "exception_object_id": 34380,
                "id": 83,
                "trace": "activesupport (6.0.2.2) lib/active_support/tagged_logging.rb:80:in `tagged'"
            },
            {
                "exception_object_id": 34380,
                "id": 84,
                "trace": "railties (6.0.2.2) lib/rails/rack/logger.rb:26:in `call'"
            },
            {
                "exception_object_id": 34380,
                "id": 85,
                "trace": "actionpack (6.0.2.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'"
            },
            {
                "exception_object_id": 34380,
                "id": 86,
                "trace": "request_store (1.5.0) lib/request_store/middleware.rb:19:in `call'"
            },
            {
                "exception_object_id": 34380,
                "id": 87,
                "trace": "actionpack (6.0.2.2) lib/action_dispatch/middleware/request_id.rb:27:in `call'"
            },
            {
                "exception_object_id": 34380,
                "id": 88,
                "trace": "rack (2.2.2) lib/rack/runtime.rb:22:in `call'"
            },
            {
                "exception_object_id": 34380,
                "id": 89,
                "trace": "activesupport (6.0.2.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'"
            },
            {
                "exception_object_id": 34380,
                "id": 90,
                "trace": "actionpack (6.0.2.2) lib/action_dispatch/middleware/executor.rb:14:in `call'"
            },
            {
                "exception_object_id": 34380,
                "id": 91,
                "trace": "actionpack (6.0.2.2) lib/action_dispatch/middleware/static.rb:126:in `call'"
            },
            {
                "exception_object_id": 34380,
                "id": 92,
                "trace": "rack (2.2.2) lib/rack/sendfile.rb:110:in `call'"
            },
            {
                "exception_object_id": 34380,
                "id": 93,
                "trace": "actionpack (6.0.2.2) lib/action_dispatch/middleware/host_authorization.rb:83:in `call'"
            },
            {
                "exception_object_id": 34380,
                "id": 94,
                "trace": "rack-cors (1.1.1) lib/rack/cors.rb:100:in `call'"
            },
            {
                "exception_object_id": 34380,
                "id": 95,
                "trace": "railties (6.0.2.2) lib/rails/engine.rb:526:in `call'"
            },
            {
                "exception_object_id": 34380,
                "id": 96,
                "trace": "puma (4.3.3) lib/puma/configuration.rb:228:in `call'"
            },
            {
                "exception_object_id": 34380,
                "id": 97,
                "trace": "puma (4.3.3) lib/puma/server.rb:682:in `handle_request'"
            },
            {
                "exception_object_id": 34380,
                "id": 98,
                "trace": "puma (4.3.3) lib/puma/server.rb:472:in `process_client'"
            },
            {
                "exception_object_id": 34380,
                "id": 99,
                "trace": "puma (4.3.3) lib/puma/server.rb:328:in `block in run'"
            },
            {
                "exception_object_id": 34380,
                "id": 100,
                "trace": "puma (4.3.3) lib/puma/thread_pool.rb:134:in `block in spawn_thread'"
            }
        ]
```

**Comment by celsodantas** [comment]
Hey @nilay thanks for the report. 

I'm not using this gem myself anymore, so I'll take a look into the issue when I have some time.

PRs are welcome too. =)
